# File Transfer Configuration of sender

# SSH Jump Server Configuration
ssh:
  # jump_server: "192.168.31.123"       # Jump server hostname or IP address
  # jump_user: "root"                    # Username for SSH connection
  # jump_port: 22                            # SSH port (default: 22)
  # jump_server: "20.30.80.249"       # Jump server hostname or IP address
  # jump_user: "zfwj"                    # Username for SSH connection
  # jump_port: 22                            # SSH port (default: 22)
  jump_server: "45.145.74.109"       # Jump server hostname or IP address
  jump_user: "root"                    # Username for SSH connection
  jump_port: 5222                            # SSH port (default: 22)
  identity_file: null                    # Optional: Path to SSH private key
  use_password: true                      # Set to true to use password auth instead of key
  password: null                         # SSH password (if use_password=true)

# Transfer Configuration
transfer:
  remote_port: 8011                        # Port exposed on jump server
  local_port: 9022                         # Local port to forward to

# Transfer Modes
# Use one of the following sections depending on your operation mode

# Sender Configuration
sender:
  enabled: true                            # Set to true to enable sender mode
  file: "~/Anaconda3-2024.10-1-Linux-x86_64.sh"            # Path to the file to send
  # file: "~/Anaconda3-2023.03-Linux-x86_64.sh"            # Path to the file to send

# Receiver Configuration
receiver:
  enabled: false                           # Set to true to enable receiver mode
  output_dir: "~/received_files"           # Directory to save received files

# Performance Tuning
performance:
  buffer_size: 65536                       # Default buffer size in bytes
  auto_adjust: true                        # Automatically adjust buffer based on network conditions
  use_adaptive_transfer: true              # Use adaptive transfer optimization

# Operation Mode
mode: "file"                               # Transfer mode: "message" or "file"
start_local_server: true                         # Start local receiver or message service
start_client: true                      # start client connection

# Progress Observer Options
progress:
  use_progress_observer: true              # Enable progress observer
  use_rich_progress: true                  # Use Rich progress bars (if available)
