# File Transfer Configuration of sender

# SSH Jump Server Configuration
ssh:
  jump_server: "45.145.74.109"       # Jump server hostname or IP address
  jump_user: "root"                    # Username for SSH connection
  jump_port: 22                            # SSH port (default: 22)
  identity_file: "/path/to/private_key"    # Optional: Path to SSH private key
  use_password: true                      # Set to true to use password auth instead of key

# Transfer Configuration
transfer:
  port: 9898                               # Port used for data transfer

# Transfer Modes
# Use one of the following sections depending on your operation mode

# Sender Configuration
sender:
  enabled: true                            # Set to true to enable sender mode
  file: "/mnt/d/Movies/Wicked.2024.Bluray.1080p.x265.Atmos.TrueHD.7.1-CarPT.mkv"            # Path to the file to send

# Receiver Configuration
receiver:
  enabled: false                           # Set to true to enable receiver mode
  output_dir: "./received_files"           # Directory to save received files

# Performance Tuning
performance:
  buffer_size: 4096                        # Default buffer size in bytes
  auto_adjust: true                        # Automatically adjust buffer based on network conditions
